### ISSUE TITLE
If I use this in my app, do I have to make the app free?

### ISSUE THREAD

**Issue by testmaster217** [shenghe/FreeSQLiteEncryption#3]
I don't imagine I will be changing anything about the library if that matters. Also, before someone says "Read the license." and closes the question before I can respond like what happened the last time I asked something like this, I did read the license and I'm still not clear. That's why I'm asking this question.

**Comment by shenghe** [comment]
Apache license is a business friendly license. you don't have to make the app free.

**Comment by testmaster217** [comment]
Thank you.
